@extends('layouts.app')

@section('title', 'Create Ticket | Issue Ticketing Log')

@section('content')
    <div data-page="ticket-create">
        <div class="content-header">
            <div>
                <p class="content-eyebrow mb-2">Submit Request</p>
                <h1 class="content-title mb-2">Create Ticket</h1>
                <p class="content-subtitle mb-0">
                    Describe the issue clearly. System fields such as ticket code, user, and audit fields are generated by the backend.
                </p>
            </div>
        </div>

        <section class="panel-card form-panel">
            <div class="state-message state-message-error d-none" data-ticket-form-error></div>
            <div class="state-message state-message-success d-none" data-ticket-form-success></div>

            <form class="ticket-form" data-ticket-create-form novalidate>
                <div>
                    <label class="form-label" for="issues">Issue title</label>
                    <input class="form-control form-control-lg" id="issues" name="issues" type="text" minlength="5" required>
                    <div class="field-error" data-error-for="issues"></div>
                </div>

                <div>
                    <label class="form-label" for="description">Description</label>
                    <textarea class="form-control" id="description" name="description" rows="6" required></textarea>
                    <div class="field-error" data-error-for="description"></div>
                </div>

                <div class="form-grid-2">
                    <div>
                        <label class="form-label" for="severity_level">Severity</label>
                        <select class="form-select" id="severity_level" name="severity_level" required>
                            <option value="">Select severity</option>
                            <option value="low">Low</option>
                            <option value="medium">Medium</option>
                            <option value="high">High</option>
                            <option value="critical">Critical</option>
                        </select>
                        <div class="field-error" data-error-for="severity_level"></div>
                    </div>

                    <div>
                        <label class="form-label" for="priority_level">Priority</label>
                        <select class="form-select" id="priority_level" name="priority_level" required>
                            <option value="">Select priority</option>
                            <option value="low">Low</option>
                            <option value="medium">Medium</option>
                            <option value="high">High</option>
                            <option value="urgent">Urgent</option>
                        </select>
                        <div class="field-error" data-error-for="priority_level"></div>
                    </div>
                </div>

                <div>
                    <label class="form-label" for="staff_id">Staff ID</label>
                    <input class="form-control" id="staff_id" name="staff_id" type="text" placeholder="Optional UUID v7">
                    <div class="field-error" data-error-for="staff_id"></div>
                </div>

                <div class="form-actions">
                    <a class="btn btn-light" href="{{ route('tickets.index') }}">Cancel</a>
                    <button class="btn btn-primary" type="submit" data-ticket-create-submit>Create ticket</button>
                </div>
            </form>
        </section>
    </div>
@endsection
